version: "3.9"

services:
  fpgadev:
    build:
      args:
          - GID=1000
          - UID=1000
          - USERNAME=aifpga
      context: .
      dockerfile: ../.docker/Dockerfile
    image: skrjtech/fpga:intel_sample
    hostname: fpga.local
    container_name: fpgadev_container
    tty: true
    restart: always
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ..:/Workspace
    mem_limit: 8g